---
title: 'My time in DC'
description: 'Visiting the Capitol'
date: Dec 24 2022
---

I ran out of the huge glass doors of my hotel, expecting a face full of cold air. 
It was 4AM and pitch black outside, so I was shocked to feel warm humidity wash over my body as I left the hotel. 
Shrugging, I jogged on, following the street lights towards the Lincoln Memorial.

It was my second time in Washington DC, but my impression was the same: this is an amazing city full of history and cultural significance. 
This isn’t anything groundbreaking, but there’s a stark difference between the west coast and the east coast that I didn’t fully appreciate until I was in my late teenage years. 
As I watched the sun rise from the steps of the Lincoln Memorial, sweating in the humid air from my morning run, I had a distinct feeling of national pride that just doesn’t come from my morning run in San Francisco.

It sounds cliche, but the air genuinely felt different. 
I mean, it was humid as hell — so the air literally felt different, but beyond that: there was more ambition and stature in a way that SF doesn’t have. 
I love the tech entrepreneur vibes of Silicon Valley, but the architecture, statues, and monuments throughout DC make a clear statement: America does not mess around. 
I can’t imagine being a foreign diplomat or royalty on a visit to Washington, driving through this impressive city on a mission to negotiate with someone — I’d be intimidated before I even began the conversation! 

On a more personal level, I was reminded of this same feeling the first time I wore a tailored suit, and the first time I wore a properly nice submariner watch. 
Even relatively simple outfit additions created meaningful behavior change for me. 
I carried myself differently, took myself more seriously, spoke more slowly. 
To this day, if I need a “confidence injection” for a big meeting or something, wearing a nice watch really has an impact. 

Okay — we can see how this plays out on a city-level: have a bunch of great architecture and monuments, and your citizens behave differently. 
And on a personal level: wear nice clothes, and you view yourself differently, which makes others view you differently. 

But how do you add “stature improvements” to a small group? 
Or put another way… how do you build culture at your startup? 
Making everyone wear a nice watch or erecting a monument in the office probably isn’t the right move (this basically sounds like an episode of Billions). 
Put the mission statement on the wall, phrased in such a way that everyone is excited about it (”Our mission is to accelerate the world’s transition to sustainable energy”)? 
That’s a good start, but there’s more to the puzzle. 
Hiring the right people is obvious, but much easier said than done. 
There’s no magic bullet for customer building, but it’s useful to look at how nations and people do it — just another way that travel expands your horizons (literally) and gives you new ideas.